### ISSUE TITLE
App doesn't start on Android 4.4.4

### ISSUE THREAD

**Issue by hiperbou** [JetBrains/kotlinconf-spinner#19]
I'm using the Play Store version with a Motorola Moto G with Android 4.4.4

> 11-03 10:28:12.182 1018-1294/? I/ActivityManager: Start proc com.jetbrains.konan_activity2 for activity com.jetbrains.konan_activity2/android.app.NativeActivity: pid=16336 uid=10224 gids={50224, 3003}
11-03 10:28:12.201 1291-3290/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 android.content.ContextWrapper.sendBroadcast:365 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
11-03 10:28:12.223 258-325/? E/cutils: Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
11-03 10:28:12.223 258-325/? W/Vold: Returning OperationFailed - no handler for errno 30
11-03 10:28:12.224 16336-16336/? W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/obb/com.jetbrains.konan_activity2
11-03 10:28:12.227 258-325/? E/cutils: Failed to mkdirat(/storage/sdcard1/Android): Read-only file system
11-03 10:28:12.227 258-325/? W/Vold: Returning OperationFailed - no handler for errno 30
11-03 10:28:12.228 16336-16336/? W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.jetbrains.konan_activity2/files
11-03 10:28:12.232 16336-16336/? E/Konan_main: runKonan_start() 44 45
11-03 10:28:12.236 16336-16348/? I/Konan_main: Entering loader...
11-03 10:28:12.236 16336-16348/? I/Konan_main: Loading openal...
11-03 10:28:12.237 16336-16348/? I/OpenAL_SLES: alc_opensles_init
11-03 10:28:12.237 16336-16348/? I/Konan_main: Loading kotlin3d...
11-03 10:28:12.242 16336-16348/? I/Konan_main: cannot load kotlin3d from /data/data/com.jetbrains.konan_activity2/lib: dlopen failed: cannot locate symbol "localeconv" referenced by "libkotlin3d.so"...
11-03 10:28:12.242 16336-16348/? I/Konan_main: Cannot load main lib, trying light...
11-03 10:28:12.242 16336-16348/? I/Konan_main: Loading kotlin3dlight...
11-03 10:28:12.247 16336-16348/? I/Konan_main: cannot load kotlin3dlight from /data/data/com.jetbrains.konan_activity2/lib: dlopen failed: cannot locate symbol "localeconv" referenced by "libkotlin3dlight.so"...
11-03 10:28:12.247 16336-16348/? I/Konan_main: Cannot load even light version, die!
11-03 10:28:12.259 1018-2488/? I/ActivityManager: Process com.jetbrains.konan_activity2 (pid 16336) has died.
11-03 10:28:12.260 1018-2488/? W/ActivityManager: Force removing ActivityRecord{42212ed8 u0 com.jetbrains.konan_activity2/android.app.NativeActivity t23}: app died, no saved state

**Comment by olonho** [comment]
Seems your libc lacks localeconv, unlikely we could fix it.

**Comment by LLChennn** [comment]
do you have any ideas?
